version: '3.9'

services:
  go-app:
    container_name: go-app
    build: .
    environment:
      DATABASE_URL: "host=go_db user=postgres password=postgres dbname=postgres sslmode=disable"
    ports:
      - "2222:2222"
    depends_on:
      - go_db
    networks:
      - api-golang-net

  go_db:
    container_name: go_db
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - api-golang-net

networks:
  api-golang-net: {}

volumes:  
  pgdata: {}